service: awstodoapi

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  gettodos:
    handler: handler.getTodos
    events:
      - http:
          path: todos
          method: get