service: awstodoapi

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  gettodos:
    handler: handler.getTodos
    events:
      - http:
          path: todos
          method: get

custom:
  stageVariables:
    todos_table: ${self:resources.Resources.DynamoDbTable.Properties.TableName}

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos-${opt:stage}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-plugin-stage-variables